# site_name: My MkDocs Site
# nav:
#   - Home: index.html
# theme:
#   name: material

site_name: My MkDocs Site
nav:
  - Home: index.html
 # - My HTML Page: html/index.html  # Thêm dòng này để chỉ định file HTML
theme:
  name: material  # hoặc theme mà bạn đã chọn
repo_url: https://github.com/your-github-username/my_mkdocs_site.git